version: "3.9"

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    image: djdocker_web
    volumes:
      - .:/var/www/html:cached
    ports:
      - "8000:8000"
    depends_on:
      - db